---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp:
  labels:
    app: simple-app
  name: simple-app
  annotations:
    flux.weave.works/tag.simple-app: glob:stg-*
    flux.weave.works/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: simple-app
    spec:
      containers:
        #public.ecr.aws/e0j8j8j7/versent-simple-app:stg-75cb7c2
      - image: docker.io/hanken16/simple-app:stg-9b34894
        name: simple-app
        resources: {}
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
          protocol: TCP
      imagePullSecrets:
      - name: dockerhub-config
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  selector:
    app: simple-app
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 80
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP #LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # nginx.ingress.kubernetes.io/upstream-hash-by: "$request_uri"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: simple-app-ingress
spec:
  rules:
  - host: simple-app.innovation-1.versent-innovation.au1.staxapp.cloud
    http:
      paths:
      - backend:
          service:
            name: simple-app
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - simple-app.innovation-1.versent-innovation.au1.staxapp.cloud
    secretName: selfsigned-cert-tls
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  #namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  #namespace: cert-manager
spec:
  dnsNames:
  - simple-app.innovation-1.versent-innovation.au1.staxapp.cloud
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-config
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodWIuZG9ja2VyLmlvIjp7ImF1dGgiOiJhR0Z1YTJWdU1UWTZjWGRsTVRJelFWTkVJVUFqQ2c9PSJ9fX0K
#eyJhdXRocyI6eyJwdWJsaWMuZWNyLmF3cyI6eyJhdXRoIjoiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsWlZ6RlVWR3hWZDFaWWF6RmlSR1JQWVRKR2JWcEVVWGRrU0dOeVZFUkNhV015WkRWV2JWSkNVV3hPZEU5Vk1EUmFWMUl3VjBSS2RrOVdUa05qYm1keVpGaFNhRTV0VFROVVYzUXpaREk0ZUdSck5IaGxSbVF4VDFac00xRlZTWHBOTWxwU1ZqTkZNMWRWVGxwU1ZWcE9ZVlJGZW1SdGFHbGtNamx5Vld0MGIyTXlPV3hWYTJRelZVaFNjMHd6YkVSUFZteDBZa1JSTVZkV1dtMWpNakZ3VDFoT1RWcEVWbGxPUjNoWlYxVjBTMHN6YUVwVlYwcHhXa1pPWVZFeFZtNVpWVzh3V1hrNVVsWnJiRU5UTVZKT1ducGtXVTlJVmxkUmFsbDJTM2wwUWxZeFl6UlRhbFphUzNwc2VrNUdaM2hWVnpGeVRtMTNjazFVWkcxa2EyaFVVVlp3ZDA1dFZqWlBWMmQ0WWxac2VWWnBkRU5TU0hCSFZUSnNWV1Z0YURCalZFazBWSHBqTlZKWWFGRmtNV3hWVFVSU2FWZElWbmRPTURGT1RraGtlR0ZyY0RSa1ZHc3dUVVZOTUdReU9YZFBSa3BoWTNwb1dGVXpRVEpqUnpGTlVteFpjbVZFUmpGUFYzaDZWak5hY0ZkR1NrSlNSM0JxVWpGd2NXSkdTalpaYkZwM1ZYcFpOVmRwT1d4VFIwMTVVbXM1Um1GVVVsTmhRemwzWWtSYWVXRXljRUpQUlRGcVlUSmFTV1ZGUlhKa01WSkVWMVJHYjFRd05WQmFWMHAxVFZjNWJXSlVUa1JVYWxKNFVteENla3N3YUZaYWJsSjNUa2hrVFdKWVFtOU5NVUV5VmpOV2NGUXpXbEZpYkdSdlRrUk9lbUl5VVhwVFNFRjVUbXRGTTJGcmIzZGhNbGw1WkROU1IyRnRPVnBXTWxWNVVsVmFSRmRGVmxKVGJsSllZMFJTY2xWVk1WbE5lbEpvVDFaV1dGWkdaRzVOTWxWNFN6Rm9iR1ZGZEVOalIyeHdVa000TkdKRVRsbFJiSEJ2VGtaQ05rNUdTakJTVlc4d1lrVldhVlZYVlhoVU1WWlhVbFJrVTA5WGRIbE5SelZNVDBkU01WbDZUVEJhVm1oV1YyMHdkbUZXYkRKaU1FcElaV2s1WVZSVldsVk5SVEZPVTIxS1IxRnJkekppVm1oYVZGZG9TMkpVV2pGaU1VRjRVMFpHYzFWWVNraGhSMHBYVGxaQ2Ewd3pTa2RqVld4RFkydFdkRlpxVm5wUmEwWTFUVVZrTldSSGVEQk9NMnhKVTBaQ2Rrd3pVVEJqUjI5M1ZUTnZjbFpZYkU5VGJGbDRVMWhuTUdKRVFrWmxWRnByVG10a1dWWXphSGRhUnpsb1RERkNWMDV0ZUZsUk0xWXpUak5PVEdGV1VscGlXRkpYVTBOek0xcFRjekprU0ZKWFYwUldhVmxxV25Wa00wbDJWa2RhZUdRelpGZE9WV3hyWVZaa1dFd3lNVEJYYlZaRVRXMVNNMDVEZEZKVFIzaFJWVmRWZDFGVGRHaGlNbmd4VVd4d2NsUXdaRWxOTWxKMVlsWmFhMHd3TlVWUFYxa3hVbFJPYTBzd05UQmFNVUY2VmpKSk1tUkhhRk5WVjFKU1pWUkZOV1ZUT1dsVlJuQjNWRVZrVWsxVVp6VmtSbFV6Vkd0V2NFMTZhSEpUTUZKcFYyczVXRmt5ZERCUFZrWjNUbTAxZEZOdE1WaGlha0V5WVVSak1sSXpSbUZoTWs1TVdXdDBNRTFxWnpCaU1HUXhXako0YW1OSGRFVk9ibEpUWVRCV2VXRnJiRVpPZWxKdFltcE9TbEl3YkhGUFYzQlFaR3hqZUU1RlRrMVZNRTV1WkVkd01WSkZUakJSVkVwdVRsYzRlR05YVWpCYWJXUXlZV3R3TVZSSVZsTlNSekZ5VmpKU1JtVkZPVFZaYXpGSVRtdFdOR1ZIU2tSaWJWSTFWMVY0YUZwR1dtcFJiR1EyV20xa1ZsSnRjRVJYV0ZwUVVsVnJkMkZHVG1saU0xSnFUbTVvTkZOclVrUmtSV1JGV1RCa2MxbFVXbEZTUlZJMVpXdHdkbUZHUlRCV2JHeEVWbFY0UlU1V2JFcFVWVFZYWldwb1ZGcHRPWHBSVjBweVRubDBXVkpXYUhsWlZUVkdZakpzYTFrd1l6RmlhVGxQWTFkYU1WZFVSbk5hUkVGM1RXMVNSRXd3TlV4WlZFcFFZV3BHY0dFd2FHMVNSbXQ0VERKNE1GbHFWVFJrU0ZsM1YxWlJkbUl3U25OT1EzUllaRlZPYldKck5VWlNibkJwVGtWd2JHRXpiM2xUUjNoUlZWWk9SRTVIV2pOaVNGWkNZekI0VDA1SE9XbGpTRlpHV2pKV2RHUXhjREZhYVhSQ1VXNVZlR1ZVYTNwU2F6RjRWMU56ZVZGNlZuWmhWRlpHWkRJNVQwOVZlRUphTUdSVFYydE9UMVpIVGpCU1YzUk5VV3BvV2xKWFdrUlVNbkJLVTFaSk1tUnBkRXRoTTFKVVRtdGtjV1ZJVW10WGFteFFWa2hhV0ZkV2FHbFhia2wyVFd4R2VWZHRjRmRPYldSQ1lWVTVibG95YkRSaFJFcEtUME4wVG1KdGNFOWphMVpGVFVkc2VGWlRPVmRqTURWSVdtMW9TV0ZyVlRSUFJHeHdaRlphTlZSR1VtcFJhVGxhVmxWM05WbFdTbmxWUlhNeVpGVTFhMU5xU214amVrWnVZakJLYms1WE5VVlRXSEJHVGtWS2RsVXdUVEJhYm5CNVYwVlNNV1ZZYkVkT2JYZ3pWMGR3WVdOWVJuSldWRnBNWXpGYVdsTXhRbmRTZWxZMFdWTTROV1ZJYkdsaU0yeHFWbXhzTWxOV2FGTlRhWE15VFZVNVQwNUZaM2RXYlhCSVlqQjBRMk50VFhsVlV6bHZVMnRHZG1FeFNYaFViVFZRVmpOc1NrMUZaek5OZW1oT1V6TkJkMlJUT1d4UmVrVXlVa1p3VTJJeVpFbGFWRlpXVjBWM01tTnVUWEpYUjI5MlQwVTVXbUpzYjNkYU0wcG9WbFpHYTFJelJtNVdNSEJ3WTFNNWNWcFVUa2xTTWpGUlpIazVkMHN3Wkc5VlYxbDRWR3BKZG1SWWJFWlNNbkJXVDBWdmVrNHlhM2ROUjFwU1dWWm9XVTFVUmpOYU1GSkxaREF4WVZOR1RrUk5SMDEyVGxWT1ZGZHFTVEZVVjA0d1VWUk9UR0pJVmpGVlZ6bFhWVzFvVkdGVVpIQk1lbFpZVjBOemVWRlViRzFUUlhNd1ZERktTbEl6U214amJUbHlVWHBqTW1GNU9WZGFTRTB4WTBVNWQySlhSa0pRVkRCcFRFTkthMWxZVW1oaE1sWTFTV3B2YVZGV1JrcFJhMFpKWVZab01sWXdPWEZpU0VJMVkyNUpjbEpJV2tsWGJtUktZbGhXVTFORE9ERlpNRFIyWVVSc00xWkhTbk5rYWxseVpXNW5lRk16WkhCWFJrWkdaVmM0TkdOVVZreFVhMlI2VVZSb1NXUlhjRlZoYVhSd1ZrWkdTbEZWUmtKUlYxcHhVV3BvUTFveWRIaGhSM1J3VW5wc00wMUZTa05rTWtadVdXNXdRMlJGUm01U1ZVWk9VakprU0ZFeFRuaFNNVTVLV1dwT1JWVlZWa2xSVmxKQ1dsVktibUpIWkc5aE1tUkRWMnhHVGxKVlJsUk9TR1JHVlZaR1RsSlVTbFpQVlVrd1UwaEplbEZVYXpObGEyeHFVVEJHYmxKV1JtNVNTRnB4WVc1d2MyTXhUbFJqTUhoRFdtcEdjV0l3YkZGaGVsbDJWREphYldWWGNGaGxiVXBQWld4Tk1sbDZVa05TZW1oVVpGUnNSRkY2VFhaa1YzQkZUVEZXVFU1cmRIRmpNMGt6WXpKb1drOUdjRU5pUXpsYVZGZFdVMXBJWjNkYU0wa3dUbXM1Y1ZaWVFrSlFWREJwVEVOS01scFlTbnBoVnpsMVNXcHZhVTFwU1hOSmJsSTFZMGRWYVU5cFNrVlJWbEpDV0RCMFJsZFRTWE5KYlZZMFkwZHNlVmxZVW5CaU1qUnBUMnBGTWsxcWF6VlBSRVY1VFVSQ09RPT0ifX19Cg==
#eyJhdXRocyI6eyJodWIuZG9ja2VyLmlvIjp7ImF1dGgiOiJhR0Z1YTJWdU1UWTZjWGRsTVRJelFWTkVJVUFqQ2c9PSJ9fX0K
type: kubernetes.io/dockerconfigjson
